language: node_js
node_js:
 - "node"

cache: npm

script: 
  - npm run test

after_success:
  - npm run build

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: 
    master: auto-trading-system
  on: master
